[package]
name = "language-gen"
version = "0.1.0"
authors = ["spacedragon <spacedragon@me.com>"]
edition = "2018"

build = "../build.rs"

[build-dependencies]
cc = "^1.0"

[dependencies]
codegen = "0.1.3"
tree-sitter = "0.16.1"
phf_codegen = "^0.8"
